name: moodle
description: A client of moodle web service API.
version: 0.0.1
homepage: https://github.com/XMUMY/XMUX

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  lints: ^1.0.0
